In [13]:
import pyarrow as pa
import pyarrow.parquet as pq
from dbfread import DBF
import os
from itertools import islice
from pathlib import Path
import pandas as pd

In [14]:
# Convert DBF to Parquet for testing and analysis
file_path = "../dataset/CAMS AMCs NAVs 09052025/11052025150310_185847860R1.dbf"
output_dir = "../dataset/CAMS AMCs NAVs 09052025/parquet"

if os.path.exists(output_dir) is False:
    os.mkdir(output_dir)
dbf = DBF(file_path)

current_code = None
buffer = []

In [15]:
# Write the products in chunks of records to avoid memory issues
for record in islice(dbf, 1_000_000):
    code = record["PRODCODE"]

    if current_code is None:
        current_code = code

    if code != current_code:
        # write current product
        table = pa.Table.from_pylist(buffer)
        pq.write_table(
            table,
            f"{output_dir}/{current_code}.parquet"
        )

        buffer = []
        current_code = code

    buffer.append(dict(record))

In [16]:
# Write the last product if any
if buffer:
    table = pa.Table.from_pylist(buffer)
    pq.write_table(
        table,
        f"{output_dir}/{current_code}.parquet"
    )

In [17]:
# Check the number of Parquet files created and their sizes
files = list(Path(output_dir).glob("*.parquet"))

print(f"Number of Parquet files: {len(files)}")

for file in files:
    print(file.name, f"{file.stat().st_size / 1024:.2f} KB")

Number of Parquet files: 2169
B02.parquet 78.72 KB
B02D.parquet 41.11 KB
B02DZ.parquet 36.14 KB
B02G.parquet 42.27 KB
B02GK.parquet 39.81 KB
B02GZ.parquet 32.17 KB
B02Z.parquet 36.09 KB
B100.parquet 47.81 KB
B1000D.parquet 9.13 KB
B1000G.parquet 9.14 KB
B1001.parquet 28.66 KB
B1001A.parquet 7.41 KB
B1001D.parquet 6.13 KB
B1001G.parquet 6.14 KB
B1001P.parquet 12.61 KB
B1002.parquet 28.59 KB
B1002D.parquet 4.13 KB
B1002G.parquet 4.15 KB
B1003.parquet 6.09 KB
B1003A.parquet 29.26 KB
B1003D.parquet 7.56 KB
B1003P.parquet 12.52 KB
B1004.parquet 28.96 KB
B1004D.parquet 6.11 KB
B1004G.parquet 6.12 KB
B1005.parquet 50.34 KB
B1005A.parquet 28.33 KB
B1005D.parquet 4.37 KB
B1005G.parquet 4.39 KB
B1005P.parquet 34.76 KB
B1006.parquet 51.15 KB
B1006G.parquet 9.94 KB
B1007.parquet 12.27 KB
B1007D.parquet 4.39 KB
B1007G.parquet 4.41 KB
B1008.parquet 12.28 KB
B1008D.parquet 6.04 KB
B1008G.parquet 6.05 KB
B1009.parquet 13.03 KB
B1009D.parquet 7.60 KB
B1009G.parquet 7.61 KB
B100A.parquet 13.74 KB
B100B.parquet 13.83 KB
B100C.parquet 13.76 KB
B100X.parquet 13.46 KB
B100Y.parquet 14.14 KB
B100Z.parquet 13.49 KB
B101.parquet 2.78 KB
B1010.parquet 13.11 KB
B1010D.parquet 7.67 KB
B1010G.parquet 7.68 KB
B1011.parquet 6.48 KB
B1011D.parquet 3.53 KB
B1011G.parquet 3.54 KB
B1012.parquet 6.49 KB
B1012D.parquet 9.53 KB
B1012G.parquet 9.54 KB
B1013.parquet 6.50 KB
B1013D.parquet 6.14 KB
B1013G.parquet 6.15 KB
B1014.parquet 6.51 KB
B1014D.parquet 4.38 KB
B1014G.parquet 4.40 KB
B1015.parquet 6.71 KB
B1015D.parquet 2.75 KB
B1015G.parquet 2.75 KB
B1016.parquet 6.72 KB
B1017.parquet 6.71 KB
B1017D.parquet 6.14 KB
B1017G.parquet 6.15 KB
B1018.parquet 6.72 KB
B1018D.parquet 3.53 KB
B1018G.parquet 3.55 KB
B1019.parquet 6.78 KB
B1019D.parquet 2.74 KB
B1019G.parquet 2.76 KB
B101A.parquet 13.32 KB
B101B.parquet 14.13 KB
B101DP.parquet 12.41 KB
B101HD.parquet 43.89 KB
B101X.parquet 14.16 KB
B101Y.parquet 14.05 KB
B102.parquet 2.79 KB
B1020.parquet 6.79 KB
B1020G.parquet 6.08 KB
B1021.parquet 6.79 KB
B1021D.parquet 6.05 KB
B1021G.parquet 6.06 KB
B1022.parquet 6.80 KB
B1022D.parquet 6.12 KB
B1022G.parquet 6.13 KB
B1023.parquet 12.38 KB
B1023D.parquet 7.50 KB
B1023G.parquet 7.51 KB
B1024.parquet 12.39 KB
B1024D.parquet 11.42 KB
B1024G.parquet 11.43 KB
B1025.parquet 6.43 KB
B1025D.parquet 6.07 KB
B1025G.parquet 6.06 KB
B1026.parquet 6.42 KB
B1026D.parquet 18.57 KB
B1026G.parquet 18.58 KB
B1027.parquet 6.43 KB
B1027D.parquet 6.07 KB
B1027G.parquet 6.08 KB
B1028.parquet 6.42 KB
B1028D.parquet 6.12 KB
B1028G.parquet 6.13 KB
B1029.parquet 31.08 KB
B1029A.parquet 10.20 KB
B1029D.parquet 13.10 KB
B1029G.parquet 13.13 KB
B1029P.parquet 16.88 KB
B102A.parquet 7.56 KB
B102B.parquet 7.49 KB
B102G.parquet 39.23 KB
B102X.parquet 7.40 KB
B102Y.parquet 7.35 KB
B103.parquet 2.78 KB
B1030.parquet 31.07 KB
B1030D.parquet 6.11 KB
B1030G.parquet 6.12 KB
B1031.parquet 17.78 KB
B1031D.parquet 7.57 KB
B1031G.parquet 7.58 KB
B1032.parquet 17.76 KB
B1032D.parquet 6.14 KB
B1032G.parquet 6.15 KB
B1033.parquet 47.39 KB
B1033A.parquet 31.58 KB
B1033D.parquet 7.70 KB
B1033G.parquet 7.71 KB
B1033P.parquet 34.47 KB
B1034.parquet 48.62 KB
B1034D.parquet 6.15 KB
B1034G.parquet 6.16 KB
B1035.parquet 17.27 KB
B1035A.parquet 6.72 KB
B1035D.parquet 6.98 KB
B1035G.parquet 6.99 KB
B1035P.parquet 8.98 KB
B1036.parquet 17.34 KB
B1036D.parquet 6.13 KB
B1036G.parquet 6.14 KB
B1037.parquet 12.32 KB
B1037D.parquet 6.13 KB
B1037G.parquet 6.14 KB
B1038.parquet 12.31 KB
B1038D.parquet 12.71 KB
B1038G.parquet 12.73 KB
B1039.parquet 2.93 KB
B1039D.parquet 3.38 KB
B1039G.parquet 3.40 KB
B103A.parquet 14.10 KB
B103B.parquet 13.29 KB
B103C.parquet 14.11 KB
B103D.parquet 35.42 KB
B103DP.parquet 9.39 KB
B103X.parquet 13.28 KB
B103Y.parquet 14.09 KB
B103Z.parquet 13.29 KB
B104.parquet 2.79 KB
B1040.parquet 9.48 KB
B1040D.parquet 6.30 KB
B1040G.parquet 6.31 KB
B1041.parquet 12.88 KB
B1041D.parquet 6.32 KB
B1041G.parquet 6.33 KB
B1042.parquet 12.86 KB
B1042D.parquet 6.06 KB
B1042G.parquet 6.05 KB
B1043.parquet 12.93 KB
B1043B.parquet 12.49 KB
B1044.parquet 12.50 KB
B1044D.parquet 3.52 KB
B1044G.parquet 3.53 KB
B1045.parquet 5.97 KB
B1045D.parquet 6.36 KB
B1045G.parquet 6.37 KB
B1046.parquet 5.96 KB
B1046D.parquet 6.09 KB
B1046G.parquet 6.11 KB
B1047.parquet 5.64 KB
B1047D.parquet 6.16 KB
B1047G.parquet 6.17 KB
B1048.parquet 5.64 KB
B1048D.parquet 6.39 KB
B1048G.parquet 6.40 KB
B1049.parquet 34.78 KB
B1049A.parquet 23.74 KB
B1049D.parquet 9.77 KB
B1049G.parquet 9.79 KB
B1049P.parquet 26.71 KB
B104A.parquet 13.22 KB
B104B.parquet 13.13 KB
B104C.parquet 13.22 KB
B104G.parquet 69.52 KB
B104X.parquet 13.35 KB
B104Y.parquet 13.42 KB
B104Z.parquet 13.39 KB
B105.parquet 2.77 KB
B1050.parquet 34.46 KB
B1050D.parquet 4.39 KB
B1050G.parquet 4.40 KB
B1051.parquet 13.64 KB
B1051D.parquet 6.04 KB
B1051G.parquet 6.04 KB
B1052.parquet 13.54 KB
B1052D.parquet 12.98 KB
B1052G.parquet 13.00 KB
B1053.parquet 13.60 KB
B1053D.parquet 6.09 KB
B1053G.parquet 6.10 KB
B1054.parquet 52.22 KB
B1054D.parquet 6.13 KB
B1054G.parquet 6.15 KB
B1055.parquet 47.22 KB
B1055D.parquet 12.61 KB
B1055G.parquet 12.62 KB
B1056.parquet 45.97 KB
B1056D.parquet 6.00 KB
B1056G.parquet 6.01 KB
B1057.parquet 49.89 KB
B1057D.parquet 6.09 KB
B1057G.parquet 6.10 KB
B1058.parquet 45.55 KB
B1058D.parquet 6.13 KB
B1058G.parquet 6.14 KB
B1059.parquet 45.52 KB
B1059D.parquet 6.09 KB
B1059G.parquet 6.10 KB
B105G.parquet 61.18 KB
B106.parquet 2.79 KB
B1060.parquet 45.88 KB
B1060D.parquet 6.10 KB
B1060G.parquet 6.11 KB
B1061.parquet 45.86 KB
B1061D.parquet 6.12 KB
B1061G.parquet 6.13 KB
B1062.parquet 45.85 KB
B1062D.parquet 4.40 KB
B1062G.parquet 4.41 KB
B1063D.parquet 2.74 KB
B1063G.parquet 2.75 KB
B1064D.parquet 2.74 KB
B1064G.parquet 2.75 KB
B1065D.parquet 2.74 KB
B1065G.parquet 2.75 KB
B1066D.parquet 3.54 KB
B1066G.parquet 3.56 KB
B1068D.parquet 2.74 KB
B1068G.parquet 2.75 KB
B1069D.parquet 6.06 KB
B1069G.parquet 6.07 KB
B106D.parquet 53.46 KB
B106DP.parquet 30.55 KB
B107.parquet 2.77 KB
B1070D.parquet 6.06 KB
B1070G.parquet 6.07 KB
B1071D.parquet 6.09 KB
B1071G.parquet 6.10 KB
B1072D.parquet 6.08 KB
B1072G.parquet 6.09 KB
B1073D.parquet 6.10 KB
B1073G.parquet 6.11 KB
B1074D.parquet 9.24 KB
B1074G.parquet 9.26 KB
B1075G.parquet 12.59 KB
B1076D.parquet 6.16 KB
B1076G.parquet 6.17 KB
B1077D.parquet 2.76 KB
B1077G.parquet 2.73 KB
B1078D.parquet 6.09 KB
B1078G.parquet 6.06 KB
B1079G.parquet 13.06 KB
B107DP.parquet 10.20 KB
B107GS.parquet 2.70 KB
B107WD.parquet 45.77 KB
B108.parquet 2.79 KB
B1080D.parquet 12.65 KB
B1080G.parquet 12.67 KB
B1081D.parquet 13.26 KB
B1081G.parquet 13.28 KB
B1082G.parquet 13.22 KB
B1083D.parquet 2.82 KB
B1083G.parquet 2.83 KB
B1084D.parquet 12.59 KB
B1084G.parquet 12.60 KB
B1085G.parquet 12.67 KB
B1086D.parquet 7.63 KB
B1086G.parquet 7.64 KB
B1087G.parquet 12.48 KB
B1088D.parquet 6.18 KB
B1088G.parquet 6.19 KB
B1089D.parquet 6.22 KB
B1089G.parquet 6.23 KB
B108A.parquet 13.06 KB
B108B.parquet 13.64 KB
B108X.parquet 13.10 KB
B108Y.parquet 12.89 KB
B109.parquet 2.77 KB
B1090D.parquet 7.94 KB
B1090G.parquet 7.96 KB
B1091D.parquet 13.36 KB
B1091G.parquet 13.37 KB
B1092D.parquet 2.82 KB
B1092G.parquet 2.83 KB
B1093D.parquet 2.82 KB
B1093G.parquet 2.83 KB
B1094A.parquet 9.15 KB
B1094B.parquet 12.46 KB
B1094C.parquet 12.41 KB
B1094X.parquet 2.86 KB
B1094Y.parquet 12.55 KB
B1094Z.parquet 2.87 KB
B1095A.parquet 7.85 KB
B1095B.parquet 7.78 KB
B1095C.parquet 7.78 KB
B1095X.parquet 7.96 KB
B1095Y.parquet 7.85 KB
B1095Z.parquet 7.97 KB
B1096A.parquet 6.30 KB
B1096B.parquet 6.30 KB
B1096C.parquet 6.37 KB
B1096X.parquet 6.35 KB
B1096Y.parquet 6.34 KB
B1096Z.parquet 6.29 KB
B1097A.parquet 2.87 KB
B1097B.parquet 2.87 KB
B1097C.parquet 2.88 KB
B1097X.parquet 2.86 KB
B1097Y.parquet 2.86 KB
B1097Z.parquet 2.87 KB
B1098A.parquet 13.95 KB
B1098B.parquet 13.86 KB
B1098C.parquet 13.12 KB
B1098X.parquet 13.25 KB
B1098Y.parquet 13.17 KB
B1098Z.parquet 13.27 KB
B1099A.parquet 6.31 KB
B1099B.parquet 6.25 KB
B1099C.parquet 6.40 KB
B1099X.parquet 6.31 KB
B1099Y.parquet 6.32 KB
B1099Z.parquet 6.36 KB
B109A.parquet 13.22 KB
B109B.parquet 13.00 KB
B109X.parquet 13.60 KB
B109Y.parquet 13.65 KB
B11.parquet 37.23 KB
B110.parquet 2.78 KB
B1100A.parquet 2.88 KB
B1100B.parquet 2.87 KB
B1100C.parquet 2.88 KB
B1100X.parquet 2.87 KB
B1100Y.parquet 2.86 KB
B1100Z.parquet 2.87 KB
B1101A.parquet 9.10 KB
B1101B.parquet 9.18 KB
B1101C.parquet 6.25 KB
B1101X.parquet 9.18 KB
B1101Y.parquet 9.22 KB
B1101Z.parquet 2.87 KB
B1102A.parquet 2.87 KB
B1102B.parquet 2.87 KB
B1102C.parquet 2.88 KB
B1102X.parquet 2.86 KB
B1102Y.parquet 2.86 KB
B1102Z.parquet 2.87 KB
B1103A.parquet 6.35 KB
B1103B.parquet 6.36 KB
B1103C.parquet 6.36 KB
B1103X.parquet 6.33 KB
B1103Y.parquet 6.35 KB
B1103Z.parquet 6.36 KB
B1104X.parquet 2.80 KB
B1105A.parquet 6.36 KB
B1105B.parquet 6.34 KB
B1105C.parquet 6.34 KB
B1105X.parquet 6.36 KB
B1105Y.parquet 6.37 KB
B1105Z.parquet 2.87 KB
B1106A.parquet 2.91 KB
B1106B.parquet 9.43 KB
B1106C.parquet 9.20 KB
B1106X.parquet 9.19 KB
B1106Y.parquet 9.20 KB
B1106Z.parquet 2.87 KB
B1107A.parquet 2.81 KB
B1107B.parquet 2.81 KB
B1107C.parquet 2.82 KB
B1107X.parquet 2.80 KB
B1107Y.parquet 2.80 KB
B1107Z.parquet 2.81 KB
B1108A.parquet 6.28 KB
B1108B.parquet 6.27 KB
B1108C.parquet 6.36 KB
B1108X.parquet 6.27 KB
B1108Y.parquet 6.25 KB
B1108Z.parquet 6.35 KB
B1109A.parquet 6.63 KB
B1109B.parquet 6.63 KB
B1109C.parquet 6.65 KB
B1109X.parquet 6.69 KB
B1109Y.parquet 6.56 KB
B1109Z.parquet 6.67 KB
B110A.parquet 11.86 KB
B110B.parquet 11.80 KB
B110C.parquet 11.93 KB
B110X.parquet 11.59 KB
B110Y.parquet 11.68 KB
B110Z.parquet 11.66 KB
B111.parquet 2.78 KB
B1110A.parquet 6.53 KB
B1110B.parquet 6.54 KB
B1110C.parquet 6.69 KB
B1110X.parquet 6.67 KB
B1110Y.parquet 6.67 KB
B1110Z.parquet 6.59 KB
B1111A.parquet 6.30 KB
B1111B.parquet 6.31 KB
B1111C.parquet 2.88 KB
B1111X.parquet 6.38 KB
B1111Y.parquet 6.42 KB
B1111Z.parquet 2.87 KB
B1112A.parquet 2.86 KB
B1112B.parquet 18.07 KB
B1112C.parquet 2.88 KB
B1112X.parquet 11.54 KB
B1112Y.parquet 17.75 KB
B1112Z.parquet 2.87 KB
B1113A.parquet 6.23 KB
B1113B.parquet 6.36 KB
B1113C.parquet 2.88 KB
B1113X.parquet 6.33 KB
B1113Y.parquet 6.35 KB
B1113Z.parquet 2.87 KB
B1114A.parquet 6.41 KB
B1114B.parquet 6.50 KB
B1114C.parquet 2.88 KB
B1114X.parquet 6.46 KB
B1114Y.parquet 6.49 KB
B1114Z.parquet 2.87 KB
B1115A.parquet 6.41 KB
B1115B.parquet 6.42 KB
B1115C.parquet 6.45 KB
B1115X.parquet 6.41 KB
B1115Y.parquet 6.46 KB
B1115Z.parquet 6.44 KB
B1116A.parquet 2.87 KB
B1116B.parquet 2.86 KB
B1116C.parquet 2.90 KB
B1116X.parquet 2.86 KB
B1116Y.parquet 2.85 KB
B1116Z.parquet 2.89 KB
B1117A.parquet 6.42 KB
B1117B.parquet 6.43 KB
B1117C.parquet 6.41 KB
B1117X.parquet 6.40 KB
B1117Y.parquet 6.42 KB
B1117Z.parquet 6.43 KB
B1118A.parquet 6.34 KB
B1118B.parquet 6.34 KB
B1118C.parquet 6.36 KB
B1118X.parquet 6.29 KB
B1118Y.parquet 6.30 KB
B1118Z.parquet 6.32 KB
B1119A.parquet 6.33 KB
B1119B.parquet 6.34 KB
B1119C.parquet 6.27 KB
B1119X.parquet 6.31 KB
B1119Y.parquet 6.28 KB
B1119Z.parquet 6.27 KB
B111A.parquet 11.89 KB
B111B.parquet 11.47 KB
B111X.parquet 11.68 KB
B111Y.parquet 11.46 KB
B112.parquet 2.79 KB
B1120A.parquet 6.34 KB
B1120B.parquet 6.35 KB
B1120C.parquet 6.33 KB
B1120X.parquet 6.34 KB
B1120Y.parquet 6.35 KB
B1120Z.parquet 2.89 KB
B1121A.parquet 2.81 KB
B1121B.parquet 2.80 KB
B1121C.parquet 2.83 KB
B1121X.parquet 2.81 KB
B1121Y.parquet 2.79 KB
B1121Z.parquet 2.83 KB
B1122A.parquet 6.30 KB
B1122B.parquet 6.31 KB
B1122C.parquet 6.30 KB
B1122X.parquet 6.32 KB
B1122Y.parquet 6.33 KB
B1122Z.parquet 2.89 KB
B1123A.parquet 6.29 KB
B1123B.parquet 6.30 KB
B1123C.parquet 6.24 KB
B1123X.parquet 6.24 KB
B1123Y.parquet 6.31 KB
B1123Z.parquet 6.22 KB
B1124A.parquet 2.81 KB
B1124B.parquet 2.80 KB
B1124C.parquet 2.83 KB
B1124X.parquet 2.80 KB
B1124Y.parquet 2.79 KB
B1124Z.parquet 2.83 KB
B1125A.parquet 2.81 KB
B1125B.parquet 2.80 KB
B1125C.parquet 2.83 KB
B1125X.parquet 2.80 KB
B1125Y.parquet 2.79 KB
B1125Z.parquet 2.83 KB
B1126A.parquet 2.81 KB
B1126B.parquet 2.80 KB
B1126C.parquet 2.84 KB
B1126X.parquet 2.81 KB
B1126Y.parquet 2.80 KB
B1126Z.parquet 2.83 KB
B1127A.parquet 6.35 KB
B1127B.parquet 6.36 KB
B1127C.parquet 2.90 KB
B1127X.parquet 2.87 KB
B1127Y.parquet 6.32 KB
B1127Z.parquet 2.90 KB
B1128A.parquet 6.34 KB
B1128B.parquet 6.35 KB
B1128C.parquet 6.33 KB
B1128X.parquet 6.31 KB
B1128Y.parquet 6.30 KB
B1128Z.parquet 6.27 KB
B1129A.parquet 8.48 KB
B1129B.parquet 12.92 KB
B1129C.parquet 12.54 KB
B1129X.parquet 13.13 KB
B1129Y.parquet 12.65 KB
B1129Z.parquet 12.47 KB
B112A.parquet 11.27 KB
B112B.parquet 11.79 KB
B112C.parquet 11.33 KB
B112G.parquet 7.97 KB
B112X.parquet 11.37 KB
B112Y.parquet 11.79 KB
B112Z.parquet 11.43 KB
B113.parquet 3.29 KB
B1130A.parquet 18.26 KB
B1130B.parquet 18.79 KB
B1130C.parquet 15.11 KB
B1130X.parquet 18.51 KB
B1130Y.parquet 19.12 KB
B1130Z.parquet 6.32 KB
B1131A.parquet 12.55 KB
B1131B.parquet 12.36 KB
B1131C.parquet 6.24 KB
B1131X.parquet 6.33 KB
B1131Y.parquet 13.19 KB
B1131Z.parquet 2.98 KB
B1132A.parquet 12.48 KB
B1132B.parquet 12.70 KB
B1132C.parquet 12.56 KB
B1132X.parquet 6.24 KB
B1132Y.parquet 12.51 KB
B1132Z.parquet 6.33 KB
B1133A.parquet 6.33 KB
B1133B.parquet 12.88 KB
B1133C.parquet 6.27 KB
B1133X.parquet 2.98 KB
B1133Y.parquet 12.92 KB
B1133Z.parquet 2.98 KB
B1134A.parquet 15.39 KB
B1134B.parquet 15.50 KB
B1134C.parquet 6.29 KB
B1134X.parquet 15.25 KB
B1134Y.parquet 15.47 KB
B1134Z.parquet 6.31 KB
B1135A.parquet 18.11 KB
B1135B.parquet 20.46 KB
B1135C.parquet 19.91 KB
B1135X.parquet 2.86 KB
B1135Y.parquet 19.03 KB
B1135Z.parquet 2.88 KB
B1136A.parquet 12.36 KB
B1136B.parquet 12.64 KB
B1136C.parquet 13.08 KB
B1136X.parquet 13.13 KB
B1136Y.parquet 13.22 KB
B1136Z.parquet 6.32 KB
B1137A.parquet 4.82 KB
B1137B.parquet 4.83 KB
B1137X.parquet 4.82 KB
B1137Y.parquet 4.82 KB
B1138A.parquet 3.67 KB
B1138B.parquet 3.66 KB
B1138X.parquet 3.65 KB
B1138Y.parquet 3.65 KB
B1139A.parquet 3.11 KB
B1139B.parquet 3.11 KB
B1139X.parquet 3.11 KB
B1139Y.parquet 3.10 KB
B113A.parquet 11.21 KB
B113B.parquet 11.31 KB
B113D.parquet 7.92 KB
B113X.parquet 11.76 KB
B113Y.parquet 11.40 KB
B114.parquet 3.07 KB
B1140A.parquet 13.17 KB
B1140B.parquet 12.98 KB
B1140C.parquet 6.31 KB
B1140X.parquet 6.18 KB
B1140Y.parquet 12.95 KB
B1140Z.parquet 12.52 KB
B1141A.parquet 13.15 KB
B1141B.parquet 13.15 KB
B1141C.parquet 13.01 KB
B1141X.parquet 12.62 KB
B1141Y.parquet 12.61 KB
B1141Z.parquet 12.82 KB
B1142A.parquet 12.59 KB
B1142B.parquet 15.71 KB
B1142C.parquet 15.82 KB
B1142X.parquet 6.29 KB
B1142Y.parquet 15.51 KB
B1142Z.parquet 6.29 KB
B1143A.parquet 3.64 KB
B1143B.parquet 3.63 KB
B1143X.parquet 3.63 KB
B1143Y.parquet 3.63 KB
B1144A.parquet 3.10 KB
B1144B.parquet 3.10 KB
B1144X.parquet 3.10 KB
B1144Y.parquet 3.09 KB
B1145A.parquet 6.28 KB
B1145B.parquet 13.19 KB
B1145C.parquet 13.12 KB
B1145X.parquet 12.47 KB
B1145Y.parquet 12.49 KB
B1145Z.parquet 2.89 KB
B1146A.parquet 12.44 KB
B1146B.parquet 12.48 KB
B1146C.parquet 9.55 KB
B1146X.parquet 9.67 KB
B1146Y.parquet 12.99 KB
B1146Z.parquet 2.98 KB
B1147A.parquet 3.64 KB
B1147B.parquet 3.64 KB
B1147X.parquet 3.64 KB
B1147Y.parquet 3.64 KB
B1148A.parquet 12.45 KB
B1148B.parquet 12.46 KB
B1148C.parquet 13.11 KB
B1148X.parquet 12.40 KB
B1148Y.parquet 12.48 KB
B1148Z.parquet 2.89 KB
B1149A.parquet 2.87 KB
B1149B.parquet 2.86 KB
B1149C.parquet 2.90 KB
B1149X.parquet 2.87 KB
B1149Y.parquet 2.86 KB
B1149Z.parquet 2.89 KB
B114A.parquet 11.43 KB
B114B.parquet 11.78 KB
B114G.parquet 26.08 KB
B114X.parquet 11.23 KB
B114Y.parquet 11.23 KB
B115.parquet 2.77 KB
B1150A.parquet 6.28 KB
B1150B.parquet 6.29 KB
B1150C.parquet 6.31 KB
B1150X.parquet 2.86 KB
B1150Y.parquet 6.21 KB
B1150Z.parquet 2.89 KB
B1151A.parquet 3.65 KB
B1151B.parquet 3.65 KB
B1151X.parquet 3.64 KB
B1151Y.parquet 3.64 KB
B1152A.parquet 12.79 KB
B1152B.parquet 13.00 KB
B1152C.parquet 13.06 KB
B1152X.parquet 12.90 KB
B1152Y.parquet 13.03 KB
B1152Z.parquet 2.89 KB
B1153A.parquet 12.67 KB
B1153B.parquet 12.68 KB
B1153C.parquet 12.59 KB
B1153X.parquet 13.30 KB
B1153Y.parquet 13.31 KB
B1153Z.parquet 2.98 KB
B1154A.parquet 2.81 KB
B1154B.parquet 2.80 KB
B1154C.parquet 2.83 KB
B1154X.parquet 2.80 KB
B1154Y.parquet 2.79 KB
B1154Z.parquet 2.83 KB
B1155A.parquet 2.81 KB
B1155B.parquet 2.80 KB
B1155C.parquet 2.84 KB
B1155X.parquet 2.81 KB
B1155Y.parquet 2.80 KB
B1155Z.parquet 2.83 KB
B1156A.parquet 6.32 KB
B1156B.parquet 13.22 KB
B1156C.parquet 6.32 KB
B1156X.parquet 2.98 KB
B1156Y.parquet 13.07 KB
B1156Z.parquet 6.32 KB
B1157A.parquet 6.23 KB
B1157B.parquet 6.24 KB
B1157C.parquet 6.26 KB
B1157X.parquet 6.28 KB
B1157Y.parquet 6.29 KB
B1157Z.parquet 2.89 KB
B1158A.parquet 3.65 KB
B1158B.parquet 3.65 KB
B1158X.parquet 3.65 KB
B1158Y.parquet 3.65 KB
B1159A.parquet 6.22 KB
B1159B.parquet 6.30 KB
B1159C.parquet 6.28 KB
B1159X.parquet 6.26 KB
B1159Y.parquet 6.30 KB
B1159Z.parquet 6.31 KB
B115A.parquet 11.18 KB
B115B.parquet 11.40 KB
B115D.parquet 26.07 KB
B115X.parquet 11.00 KB
B115Y.parquet 11.13 KB
B116.parquet 2.79 KB
B1160A.parquet 2.86 KB
B1160B.parquet 2.85 KB
B1160X.parquet 2.86 KB
B1160Y.parquet 2.85 KB
B1161A.parquet 6.25 KB
B1161B.parquet 12.57 KB
B1161C.parquet 12.60 KB
B1161X.parquet 12.87 KB
B1161Y.parquet 12.49 KB
B1161Z.parquet 6.31 KB
B1162A.parquet 2.81 KB
B1162B.parquet 2.80 KB
B1162C.parquet 2.83 KB
B1162X.parquet 2.80 KB
B1162Y.parquet 2.79 KB
B1162Z.parquet 2.83 KB
B1163A.parquet 2.80 KB
B1163B.parquet 2.79 KB
B1163X.parquet 2.80 KB
B1163Y.parquet 2.79 KB
B1164A.parquet 2.98 KB
B1164B.parquet 12.71 KB
B1164C.parquet 6.31 KB
B1164X.parquet 6.27 KB
B1164Y.parquet 13.17 KB
B1164Z.parquet 6.27 KB
B1165A.parquet 11.51 KB
B1165B.parquet 12.49 KB
B1165C.parquet 2.98 KB
B1165X.parquet 11.91 KB
B1165Y.parquet 12.60 KB
B1165Z.parquet 11.55 KB
B1166A.parquet 2.81 KB
B1166B.parquet 2.80 KB
B1166C.parquet 2.83 KB
B1166X.parquet 2.80 KB
B1166Y.parquet 2.79 KB
B1166Z.parquet 2.83 KB
B1167A.parquet 2.80 KB
B1167B.parquet 2.79 KB
B1167X.parquet 2.80 KB
B1167Y.parquet 2.79 KB
B1168B.parquet 13.23 KB
B1168Y.parquet 13.25 KB
B1169A.parquet 6.22 KB
B1169B.parquet 6.23 KB
B1169C.parquet 6.21 KB
B1169X.parquet 6.23 KB
B1169Y.parquet 6.23 KB
B1169Z.parquet 6.26 KB
B116A.parquet 11.04 KB
B116B.parquet 11.34 KB
B116G.parquet 15.17 KB
B116X.parquet 11.35 KB
B116Y.parquet 11.27 KB
B117.parquet 2.77 KB
B1170A.parquet 6.26 KB
B1170B.parquet 6.27 KB
B1170C.parquet 6.26 KB
B1170X.parquet 2.86 KB
B1170Y.parquet 6.15 KB
B1170Z.parquet 6.11 KB
B1171A.parquet 12.42 KB
B1171B.parquet 12.56 KB
B1171C.parquet 12.43 KB
B1171X.parquet 7.76 KB
B1171Y.parquet 12.40 KB
B1171Z.parquet 2.89 KB
B1172A.parquet 6.25 KB
B1172B.parquet 6.25 KB
B1172C.parquet 6.24 KB
B1172X.parquet 6.22 KB
B1172Y.parquet 6.24 KB
B1172Z.parquet 2.89 KB
B1173A.parquet 6.22 KB
B1173B.parquet 6.28 KB
B1173C.parquet 6.24 KB
B1173X.parquet 6.21 KB
B1173Y.parquet 6.29 KB
B1173Z.parquet 6.27 KB
B1174A.parquet 12.80 KB
B1174B.parquet 12.81 KB
B1174C.parquet 12.47 KB
B1174X.parquet 13.11 KB
B1174Y.parquet 13.24 KB
B1174Z.parquet 2.98 KB
B1175A.parquet 16.59 KB
B1175B.parquet 16.63 KB
B1175C.parquet 16.14 KB
B1175X.parquet 2.87 KB
B1175Y.parquet 16.71 KB
B1175Z.parquet 7.30 KB
B1176B.parquet 12.89 KB
B1176Y.parquet 13.27 KB
B1177A.parquet 2.87 KB
B1177B.parquet 2.86 KB
B1177C.parquet 2.89 KB
B1177X.parquet 2.86 KB
B1177Y.parquet 2.85 KB
B1177Z.parquet 2.89 KB
B1178A.parquet 2.88 KB
B1178B.parquet 13.13 KB
B1178C.parquet 2.90 KB
B1178X.parquet 6.26 KB
B1178Y.parquet 15.72 KB
B1178Z.parquet 2.89 KB
B1179A.parquet 3.79 KB
B1179B.parquet 3.80 KB
B1179X.parquet 3.78 KB
B1179Y.parquet 3.79 KB
B117A.parquet 10.58 KB
B117B.parquet 10.80 KB
B117C.parquet 10.61 KB
B117D.parquet 14.01 KB
B117X.parquet 10.56 KB
B117Y.parquet 10.36 KB
B117Z.parquet 10.59 KB
B118.parquet 2.78 KB
B1180A.parquet 26.79 KB
B1180B.parquet 30.13 KB
B1180C.parquet 26.82 KB
B1180X.parquet 28.06 KB
B1180Y.parquet 30.40 KB
B1180Z.parquet 28.09 KB
B1181B.parquet 2.86 KB
B1181C.parquet 2.89 KB
B1181X.parquet 2.86 KB
B1181Y.parquet 2.85 KB
B1181Z.parquet 2.89 KB
B1182A.parquet 3.78 KB
B1182B.parquet 3.79 KB
B1182C.parquet 2.83 KB
B1182X.parquet 3.77 KB
B1182Y.parquet 3.79 KB
B1182Z.parquet 2.82 KB

In [18]:
# Check the uniqueness of the columns in each Parquet file and report any errors
errors = []

for file in files:
    df = pd.read_parquet(file)

    unique_codes = df["PRODCODE"].unique()
    unique_names = df["NAME"].unique()
    unique_schemes = df["SCHEME_TYP"].unique()
    unique_isins = df["ISIN_NO"].unique()

    if (
        len(unique_codes) != 1
        or unique_codes[0] != file.stem
        or len(unique_names) != 1
        or len(unique_schemes) != 1
        or len(unique_isins) != 1
    ):
        errors.append(
            (
                file.name,
                unique_codes,
                unique_names,
                unique_schemes,
                unique_isins
            )
        )

print("Files checked:", len(files))
print("Errors:", len(errors))

if errors:
    for error in errors[:10]:
        print(error)

Files checked: 2169
Errors: 0

In [19]:
unique_counts = []

for file in files:
    df = pd.read_parquet(file)

    result = {
        "PRODCODE_FILE": file.stem,
    }

    for col in df.columns:
        result[col] = df[col].nunique(dropna=False)

    unique_counts.append(result)

unique_counts_df = pd.DataFrame(unique_counts)

display(unique_counts_df)

,PRODCODE_FILE,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNI,CORPDIVRAT,SCHEME_TYP,ISIN_NO,SWING_NAV
0,B02,1,1,7140,5772,1,2,1,1,2
1,B02D,1,1,3632,3077,1,1,1,1,2
2,B02DZ,1,1,3040,2856,1,1,1,1,2
3,B02G,1,1,4223,2357,1,1,1,1,2
4,B02GK,1,1,3998,2255,1,1,1,1,2
...,...,...,...,...,...,...,...,...,...,...
2164,B1391A,1,1,727,715,1,1,1,1,1
2165,B1391B,1,1,727,714,1,1,1,1,1
2166,B1391C,1,1,727,707,1,1,1,1,1
2167,B1391X,1,1,727,715,1,1,1,1,1
2168,B1391Y,1,1,548,535,1,1,1,1,1

In [20]:
# Check the uniqueness of the columns and find any columns that have constant values across files
unique_counts_check = []

for col in unique_counts_df.columns:
    unique_values = unique_counts_df[col].unique()

    unique_counts_check.append({
        "COLUMN": col,
        "UNIQUE_COUNTS": unique_values,
        "NUMBER_OF_UNIQUE_COUNTS": len(unique_values),
        "CONSTANT": len(unique_values) == 1
    })

unique_counts_check_df = pd.DataFrame(unique_counts_check)

display(unique_counts_check_df)

,COLUMN,UNIQUE_COUNTS,NUMBER_OF_UNIQUE_COUNTS,CONSTANT
0,PRODCODE_FILE,"[B02, B02D, B02DZ, B02G, B02GK, B02GZ, B02Z, B...",2169,False
1,PRODCODE,[1],1,True
2,NAME,[1],1,True
3,NAV_DATE,"[7140, 3632, 3040, 4223, 3998, 3041, 3837, 482...",248,False
4,NAV_VALUE,"[5772, 3077, 2856, 2357, 2255, 2041, 2857, 327...",448,False
5,DIV_PERUNI,"[1, 2, 10, 4, 151]",5,False
6,CORPDIVRAT,"[2, 1, 3, 5, 4, 156]",6,False
7,SCHEME_TYP,[1],1,True
8,ISIN_NO,[1],1,True
9,SWING_NAV,"[2, 1]",2,False

In [21]:
# Clean up the output directory after checking

import shutil
shutil.rmtree(output_dir)